### ISSUE TITLE
Please add (or make a version) with support for mm

### ISSUE THREAD

**Issue by stevekennedyuk** [RainyDayHiker/Fusion360-WavyBowl#1]
I use everything in mm and would very much like if Wavybowl could support mm as default

**Comment by RainyDayHiker** [comment]
Added support to properly use the document's default unit to set the initial measurements and to display the size of the resulting bowl.  Also adjusts the default sizes based on whether the unit is metric or imperial.

Commit: https://github.com/RainyDayHiker/Fusion360-WavyBowl/commit/6a608b6625df2e8375c3b52ae51e50b06ddbcc49
